/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kkandroidstudy_ndk_JNI */

#ifndef _Included_com_kkandroidstudy_ndk_JNI
#define _Included_com_kkandroidstudy_ndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kkandroidstudy_ndk_JNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kkandroidstudy_ndk_JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    sayString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kkandroidstudy_ndk_JNI_sayString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kkandroidstudy_ndk_JNI_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kkandroidstudy_ndk_JNI_checkPwd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kkandroidstudy_ndk_JNI_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kkandroidstudy_ndk_JNI_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kkandroidstudy_ndk_JNI_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_kkandroidstudy_ndk_JNI
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kkandroidstudy_ndk_JNI_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
